spring.application.name=stock-service

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5436}/${POSTGRES_DB:stock_service}
spring.datasource.username=${POSTGRES_USER:stock_service}
spring.datasource.password=${POSTGRES_PASSWORD:stock_service}

spring.jpa.open-in-view=false
